teddy-console/src/main/java/com/hyl/teddy/console/entity/Payment.java
package com.hyl.teddy.console.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.springframework.format.annotation.NumberFormat;

/**
 * 订单 payment
 *
 * @author Administrator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Payment {

    @JsonIgnore
    private int id;
    private String orderno;//订单号
    @JsonIgnore
    private int deliverId;//配送方式id
    @JsonIgnore
    private int courierId;//配送员id
    private String courierNumber;
    private String courierName;
    private String courierContact;
    @JsonIgnore
    private int addressId;//地址
    private CustAddress address;
    @JsonIgnore
    private int customerId;//用户id
    private String nickname;
    private boolean vip;
    @JsonIgnore
    private int regionId;//区域
    private int restaurantId;//餐厅
    private String restaurantImg;
    private String restaurantName;
    private String restaurantLocation;
    private String restaurantContact;
    @JsonIgnore
    private int packageFeeValue;//打包费  （单位分）
    @JsonIgnore
    private int deliveryValue; //送餐费 单位分  
    /**
     * 订单状态 0-未付款 1-支付失败 2-未指派 3-配餐中 4- 缺失菜品 5-配餐完成 6-配送中 8-已完成 9- 已取消
     */
    private int status;
    private String statusDesc;//订单状态描述
    private String memo;//客户订餐备注
    private int cash;
    private int score;//此次订单可产生积分
    private String createTime;//创建时间
    private int star;//评价星级
    private String comment;//内容
    private Date commentTime;
    private boolean editable;//是否可编辑，用户客户加菜
    private List<PaymentGoods> goods = new ArrayList<PaymentGoods>();
    private List<PromotionResponse> promotions = new ArrayList<PromotionResponse>();
    @JsonIgnore
    private int paid;//实际费用 支付时候发生变化，单位：分。客户端可用来对账
    private double cost;//订单当前实际费用

    private String readyTime;//取菜确认时间
    private String assignTime;//后台分配配送员时间（配送员接单时间）

    /**
     * 订单原价：总费用 单位分
     */
    private double primeCost;
    
    public double getPrimeCost() {
		return primeCost;
	}

	public void setPrimeCost(double primeCost) {
		this.primeCost = primeCost;
	}

	public int primeCost() {
        int primeCost = 0;
        for (PaymentGoods g : goods) {
            if (g.getStatus() < 2) {	//状态不属于退菜时 参与计算
                primeCost += g.getPriceValue() * g.getCount();
            }
        }
        if (primeCost > 0) {
            primeCost += packageFeeValue;
        }
        // primeCost +=  delivery; //配送费不算入本金
        return primeCost;
    }

    private double packageFee;
    @NumberFormat(pattern = "#.##")
    public double getPackageFee() {
    	if(packageFee != 0.0){
    		return packageFee;
    	}
        return 1.0 * packageFeeValue / 100;
    }

    private double delivery;
    @NumberFormat(pattern = "#.##")
    public double getDelivery() {
    	if(delivery != 0.0){
    		return delivery;
    	}
        return 1.0 * deliveryValue / 100;
    }

    @NumberFormat(pattern = "#.##")
    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public void addGoods(PaymentGoods item) {
        this.goods.add(item);
    }

    public void addPromotion(PromotionResponse item) {
        promotions.add(item);
    }

    /**
     * 取菜任务量.
     */
    @JsonIgnore
    public int getDeliverWeight() {
        return goods.size();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getOrderno() {
        return orderno;
    }

    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    public int getDeliverId() {
        return deliverId;
    }

    public void setDeliverId(int deliverId) {
        this.deliverId = deliverId;
    }

    public int getCourierId() {
        return courierId;
    }

    public void setCourierId(int courierId) {
        this.courierId = courierId;
    }

    public int getAddressId() {
        return addressId;
    }

    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

    public CustAddress getAddress() {
        return address;
    }

    public void setAddress(CustAddress address) {
        this.address = address;
    }

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public int getRegionId() {
        return regionId;
    }

    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }

    public int getRestaurantId() {
        return restaurantId;
    }

    public void setRestaurantId(int restaurantId) {
        this.restaurantId = restaurantId;
    }

    public String getRestaurantImg() {
        return restaurantImg;
    }

    public void setRestaurantImg(String restaurantImg) {
        this.restaurantImg = restaurantImg;
    }

    public String getRestaurantName() {
        return restaurantName;
    }

    public void setRestaurantName(String restaurantName) {
        this.restaurantName = restaurantName;
    }

    public String getRestaurantLocation() {
        return restaurantLocation;
    }

    public void setRestaurantLocation(String restaurantLocation) {
        this.restaurantLocation = restaurantLocation;
    }

    public int getPackageFeeValue() {
        return packageFeeValue;
    }

    public void setPackageFeeValue(int packageFeeValue) {
        this.packageFeeValue = packageFeeValue;
    }

    public int getDeliveryValue() {
        return deliveryValue;
    }

    public void setDeliveryValue(int deliveryValue) {
        this.deliveryValue = deliveryValue;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getStatusDesc() {
        return statusDesc;
    }

    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public int getCash() {
        return cash;
    }

    public void setCash(int cash) {
        this.cash = cash;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public int getStar() {
        return star;
    }

    public void setStar(int star) {
        this.star = star;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    public List<PaymentGoods> getGoods() {
        return goods;
    }

    public void setGoods(List<PaymentGoods> goods) {
        this.goods = goods;
    }

    public List<PromotionResponse> getPromotions() {
        return promotions;
    }

    public void setPromotions(List<PromotionResponse> promotions) {
        this.promotions = promotions;
    }

    public int getPaid() {
        return paid;
    }

    public void setPaid(int paid) {
        this.paid = paid;
    }

    public String getReadyTime() {
        return readyTime;
    }

    public void setReadyTime(String readyTime) {
        this.readyTime = readyTime;
    }

    public String getAssignTime() {
        return assignTime;
    }

    public void setAssignTime(String assignTime) {
        this.assignTime = assignTime;
    }

    public boolean isVip() {
        return vip;
    }

    public void setVip(boolean vip) {
        this.vip = vip;
    }

    public String getCourierNumber() {
        return courierNumber;
    }

    public void setCourierNumber(String courierNumber) {
        this.courierNumber = courierNumber;
    }

    public String getCourierName() {
        return courierName;
    }

    public void setCourierName(String courierName) {
        this.courierName = courierName;
    }

    public String getCourierContact() {
        return courierContact;
    }

    public void setCourierContact(String courierContact) {
        this.courierContact = courierContact;
    }

    public String getRestaurantContact() {
        return restaurantContact;
    }

    public void setRestaurantContact(String restaurantContact) {
        this.restaurantContact = restaurantContact;
    }

  //订单状态 0-未付款 1-支付失败 2-未指派 3-配餐中 4- 缺失菜品 5-配餐完成 6-配送中 8-已完成 9- 已取消
  	public String getOrderStatus() {
  		switch (status) {
  		case 0:
  			return "未付款";
  		case 1:
  			return "支付失败";
  		case 2:
  			return "未指派";
  		case 3:
  			return "配餐中";
  		case 4:
  			return "缺失菜品";
  		case 5:
  			return "配餐完成";
  		case 6:
  			return "配送中";
  		case 8:
  			return "已完成";
  		case 9:
  			return "已取消";	

  		}
  				
  		return "";
  	}

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Date getCommentTime() {
        return commentTime;
    }

    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }
}

teddy-console/src/main/webapp/WEB-INF/jsp/payment/unallot/courier/form.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="/WEB-INF/jspf/prepare.jspf" %>
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8"/>
        <%@include file="/WEB-INF/jspf/head.jspf" %>
        <title><spring:message code="application.title"/></title>
    </head>
    
    <body class="${principal.skin} ${principal.navbarFixed?'navbar-fixed':''}">
        <%@include file="/WEB-INF/jspf/body-first.jspf" %>
        
        
        <form class="form-horizontal validate" method="post" role="form">
            
           <div class="form-group">
                <label class="col-sm-3 control-label" for="employeeId"><span class="text-danger">*</span>${flag}：</label>
                <div class="col-sm-5">
                    <div class="hidden">
                        <c:forEach items="${pks}" var="cur">
                            <input type="hidden" name="pks" value="${cur}" />
                        </c:forEach>
                    </div>
                    <select class="form-control" id="employeeId" name="employeeId" data-value="${payment.courierId}" data-rule-required="false">
                        <option value="0">----${flag}----</option>
                        <c:forEach items="${employees}" var="cur">
                            <option value="${cur.id}">${cur.name}</option>
                        </c:forEach>
                    </select>
                </div>
                <label class="col-sm-4 help-inline form-control-static" for="employeeId"></label>
            </div>
            
            
            <div class="clearfix form-actions">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-primary">
                        <i class="icon-ok bigger-110"></i>
                        确定提交
                    </button>

                    <button type="button" class="btn btn-info action-back">
                        <i class="icon-undo bigger-110"></i>
                        取消返回
                    </button>
                </div>
            </div>
        </form>
        <%@include file="/WEB-INF/jspf/body-last.jspf" %>
    </body>
</html>

teddy-console/src/main/webapp/WEB-INF/jsp/payment/unallot/courier/list.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="/WEB-INF/jspf/prepare.jspf"%>
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <%@include file="/WEB-INF/jspf/head.jspf"%>
        <title><spring:message code="application.title" /></title>
    </head>


    <body class="${principal.skin} ${principal.navbarFixed?'navbar-fixed':''}">
        <%@include file="/WEB-INF/jspf/body-first.jspf"%>

        <div class="row row-nocol">
            <form class="form-inline lookup" role="form" method="post">
                <div class="form-group">
                    <label class="sr-only" for="lookup-orderno">订单号</label> <input
                        id="lookup-orderno" class="form-control" name="orderno"
                        value="${lookup.orderno}" placeholder="订单号" />
                </div>

                <div class="form-group">
                    <label class="sr-only" for="lookup-mobile">客户电话</label>
                    <input id="lookup-mobile" class="form-control" name="mobile" value="${lookup.mobile}" placeholder="客户电话" />
                </div>
                <div class="form-group">
                    <label class="sr-only" for="lookup-regionId">所属区域</label>
                    <select class="form-control" id="lookup-regionId" name="regionId" data-value="${lookup.regionId}">
                        <option value="">--所属区域--</option>
                        <c:forEach items="${region}" var="cur">
                            <option value="${cur.id}">${cur.name}</option>
                        </c:forEach>
                    </select>
                </div>

                <div class="form-group form-btn-bar">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="icon-search"></i> 查询
                    </button>
                    <button type="button" class="btn btn-info btn-sm reset">
                        <i class="icon-undo"></i> 重置
                    </button>
                </div>
            </form>
        </div>

        <c:if test="${not empty remind}">
            <div class="alert alert-${remind.level}">
                <button data-dismiss="alert" class="close" type="button">
                    <i class="icon-remove"></i>
                </button>
                ${remind.message}
            </div>
        </c:if>


        <form class="row row-nocol" method="post">
            <div class="action-bar">
                <c:if test="${lookup.regionId > 0}">
                    <button class="btn btn-sm btn-info action-get" type="button"
                            data-href="allotdeliver"
                            data-checkbox-require="pks"
                            data-form="true"
                            data-confirm="true"><span class="icon-link"></span> 批量分配</button>
                </c:if>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="center"><input type="checkbox" data-member="pks" /></th>
                        <th>序号</th>
                        <th>订单号</th>
                        <th>取菜员</th>
                        <th>配送员</th>
                        <th>客户姓名</th>
                        <th>送餐地址</th>
                        <th>区域</th>
                        <th>客户电话</th>
                        <th>订单状态</th>
                        <!-- <th>订单可否编辑</th> -->
                        <th class="text-info">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <c:forEach items="${pager.elements}" var="cur" varStatus="status">
                        <tr>
                            <td class="center"><input type="checkbox" name="pks"
                                                      value="${cur.id}" /></td>
                            <td>${status.count}</td>
                            <td>${cur.orderno}</td>
                            <td>${cur.deliverName}</td>
                            <td>${cur.courierName}</td>
                            <td>${cur.customerName}</td>
                            <td>${cur.address}</td>
                            <td></td>
                            <td>${cur.mobile}</td>
                            <td>${cur.orderStatus}</td>
                            <%-- <td><span class="label label-${cur.editable ? 'info' : 'danger'} arrowed arrowed-right">${cur.editable  ? '可编辑' : '不可编辑'}</span></td> --%>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-xs btn-info action-get" data-href="${cur.orderno}/allotcourier" data-rel="tooltip" data-original-title="分配配送员" >
                                        <i class="icon-link bigger-120"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </c:forEach>
                    <c:forEach begin="${fn:length(pager.elements)}" end="${pager.size-1}">
                        <tr>
                            <td>&nbsp;</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
        </form>
        <%@include file="/WEB-INF/jspf/pager.jspf"%>
        <%@include file="/WEB-INF/jspf/body-last.jspf"%>
    </body>
</html>